# Generated by Django 4.1 on 2022-08-10 11:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JunctionPoint',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('arcid', models.FloatField(blank=True, null=True)),
                ('grid_code', models.FloatField(blank=True, null=True)),
                ('from_node', models.FloatField(blank=True, null=True)),
                ('to_node', models.FloatField(blank=True, null=True)),
                ('orig_fid', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='RiverStream',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('arcid', models.FloatField(blank=True, null=True)),
                ('grid_code', models.FloatField(blank=True, null=True)),
                ('from_node', models.FloatField(blank=True, null=True)),
                ('to_node', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='Watershed',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('gridcode', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857)),
            ],
        ),
    ]
